// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASnIACly9Rw2WOd4a2GD1-JhKJOMIx94I',
    appId: '1:97893383787:web:44628af4304f31155e7b2e',
    messagingSenderId: '97893383787',
    projectId: 'newsapp-48030',
    authDomain: 'newsapp-48030.firebaseapp.com',
    storageBucket: 'newsapp-48030.appspot.com',
    measurementId: 'G-NKN8DSWQT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrPXbkY-yo3zAIs2ZdZtllDBv5h_zemUs',
    appId: '1:97893383787:android:54b1e265b096dd285e7b2e',
    messagingSenderId: '97893383787',
    projectId: 'newsapp-48030',
    storageBucket: 'newsapp-48030.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHmwNPpHpJqVPD1qXFi4xcjTTAwLhI7tw',
    appId: '1:97893383787:ios:8ead097c1a6b59b85e7b2e',
    messagingSenderId: '97893383787',
    projectId: 'newsapp-48030',
    storageBucket: 'newsapp-48030.appspot.com',
    iosClientId: '97893383787-sop45hu7sr8rqjvdir26sdk68d8ujul5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHmwNPpHpJqVPD1qXFi4xcjTTAwLhI7tw',
    appId: '1:97893383787:ios:8ead097c1a6b59b85e7b2e',
    messagingSenderId: '97893383787',
    projectId: 'newsapp-48030',
    storageBucket: 'newsapp-48030.appspot.com',
    iosClientId: '97893383787-sop45hu7sr8rqjvdir26sdk68d8ujul5.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );
}
